### ISSUE TITLE
please update this repo 

### ISSUE THREAD

**Issue by igpucs** [grangus/open-rbx-cool#2]
Its been months since the last update ive been wanting to learn off of something like this but i would rather learn when there is no issues with this project so if you could update this it will be very appreciated!

**Comment by psyduckc** [comment]
yea pls update repo pls

**Comment by igpucs** [comment]
> yea pls update repo pls

im not sure whats his problem im not sure why post it and expect people are gonna learn off of something that doesnt work properly, He states that there is a infinite money glitch, So why would we wanna learn stuff that dont work

**Comment by grangus** [comment]
It worked when I posted it. Do you realize how long it's been since February? I'm not updating the repo. I figured you would've gotten the hint after I closed your last issue.

**Comment by grangus** [comment]
Maybe in the near future, I'll release a different open source site with much better practices, comments, and deployment instructions.
